version: '3'
services: 
    apiservapp:
        container_name: api-serv
        restart: always
        build: .
        ports: 
            - '5555:3000'
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
       